/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mwr_mercury_Common */

#ifndef _Included_com_mwr_mercury_Common
#define _Included_com_mwr_mercury_Common
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mwr_mercury_Common
 * Method:    native_strings
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mwr_mercury_Common_native_1strings
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
